services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092" # Cổng để máy thật (localhost) truy cập
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Cấu hình Listeners: tách biệt cổng 9092 và 29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-producer:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    command: python producer.py
    depends_on:
      kafka:
        condition: service_healthy # Chỉ chạy khi Kafka đã pass healthcheck
    volumes:
      - ./data/results:/app/data/results
    environment:
      KAFKA_BROKER: kafka:9092
      TOPIC_NAME: customer_clusters
      DATA_SOURCE: /app/data/results/clustered_users.parquet/part-00000-a026af0d-038b-457e-9787-32462b560651-c000.snappy.parquet # Trỏ trực tiếp vào file cụ thể

  streaming-server:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: python ws_server.py
    ports:
      - "8001:8000"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      TOPIC_NAME: customer_clusters
    
  frontend-react:
    image: node:20-slim
    working_dir: /app/frontend
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    # Lệnh cài đặt và chạy dev server
    command: >
      sh -c "npm install && npm run dev -- --port 3001 --host"
    depends_on:
      - bridge